# Generated by Django 3.1.7 on 2021-04-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=12)),
                ('desc', models.TextField(default='Not Applicable')),
                ('status', models.CharField(default='NA', max_length=10)),
                ('reply', models.TextField(default='NA', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(default='123ABC', max_length=15)),
                ('item', models.CharField(default='Dell i5 Laptop', max_length=50)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default='Apple iPhone 12', max_length=30)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
